<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StarShop Quản trị</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container d-flex gap-3 flex-wrap"><a class="navbar-brand" href="${pageContext.request.contextPath}/manager">StarShop Admin</a><div class="d-flex gap-3 flex-wrap"><a class="text-white" href="${pageContext.request.contextPath}/manager/shops">Shop</a><a class="text-white" href="${pageContext.request.contextPath}/manager/users">Người dùng</a><a class="text-white" href="${pageContext.request.contextPath}/manager/shipping-providers">Vận chuyển</a><a class="text-white" href="${pageContext.request.contextPath}/manager/orders">Đơn hàng</a></div></div></nav>
<main class="container py-4"><c:if test="${not empty success}"><div class="alert alert-success"><c:out value="${success}"/></div></c:if><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<h1 class="h3">Theo dõi và phân công đơn hàng</h1><form method="get" class="d-flex gap-2 my-3"><select class="form-select" name="status"><option value="">Mọi trạng thái</option><c:forEach items="${statuses}" var="item"><option value="${item}" ${selectedStatus == item ? 'selected' : ''}>${item}</option></c:forEach></select><button class="btn btn-primary">Lọc</button></form>
<c:forEach items="${orders.content}" var="order"><div class="card mb-3 shadow-sm"><div class="card-body"><div class="d-flex flex-wrap justify-content-between"><h2 class="h5">Đơn #${order.id} · <c:out value="${order.shop.name}"/></h2><span class="badge text-bg-secondary">${order.status}</span></div><p class="mb-1"><c:out value="${order.receiverName}"/> · <c:out value="${order.receiverPhone}"/></p><p><c:out value="${order.shippingAddress}"/> · ${order.totalAmount} VND</p>
<c:if test="${order.status == 'READY_FOR_PICKUP'}"><form method="post" action="${pageContext.request.contextPath}/manager/orders/${order.id}/assign" class="row g-2"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><div class="col-md-3"><label class="form-label">Shipper</label><select name="shipperId" class="form-select" required><option value="">Chọn shipper</option><c:forEach items="${shippers}" var="shipper"><option value="${shipper.id}"><c:out value="${shipper.fullName}"/> · <c:out value="${shipper.email}"/></option></c:forEach></select></div><div class="col-md-3"><label class="form-label">Đơn vị vận chuyển</label><select name="providerId" class="form-select" required><option value="">Chọn đơn vị</option><c:forEach items="${providers}" var="provider"><option value="${provider.id}"><c:out value="${provider.name}"/></option></c:forEach></select></div><div class="col-md-4"><label class="form-label">Ghi chú</label><input name="note" maxlength="500" class="form-control"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary">Phân công</button></div></form></c:if>
</div></div></c:forEach><c:if test="${orders.isEmpty()}"><div class="alert alert-secondary">Không có đơn hàng phù hợp</div></c:if>
<nav class="mt-3"><ul class="pagination"><c:if test="${orders.hasPrevious()}"><c:url var="prev" value="/manager/orders"><c:param name="page" value="${orders.number-1}"/><c:param name="status" value="${selectedStatus}"/></c:url><li class="page-item"><a class="page-link" href="${prev}">Trước</a></li></c:if><li class="page-item disabled"><span class="page-link">${orders.number+1} / ${orders.totalPages == 0 ? 1 : orders.totalPages}</span></li><c:if test="${orders.hasNext()}"><c:url var="next" value="/manager/orders"><c:param name="page" value="${orders.number+1}"/><c:param name="status" value="${selectedStatus}"/></c:url><li class="page-item"><a class="page-link" href="${next}">Sau</a></li></c:if></ul></nav></main></body></html>
