<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StarShop Quản trị</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container d-flex gap-3 flex-wrap"><a class="navbar-brand" href="${pageContext.request.contextPath}/manager">StarShop Admin</a><div class="d-flex gap-3 flex-wrap"><a class="text-white" href="${pageContext.request.contextPath}/manager/shops">Shop</a><a class="text-white" href="${pageContext.request.contextPath}/manager/users">Người dùng</a><a class="text-white" href="${pageContext.request.contextPath}/manager/shipping-providers">Vận chuyển</a><a class="text-white" href="${pageContext.request.contextPath}/manager/orders">Đơn hàng</a></div></div></nav>
<main class="container py-4"><c:if test="${not empty success}"><div class="alert alert-success"><c:out value="${success}"/></div></c:if><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<h1 class="h3 mb-3">Đơn vị vận chuyển</h1><div class="row g-4"><div class="col-lg-5"><div class="card p-3"><h2 class="h5">${empty providerForm.id ? 'Thêm đơn vị' : 'Sửa đơn vị'}</h2>
<form:form modelAttribute="providerForm" method="post" action="${pageContext.request.contextPath}/manager/shipping-providers"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><form:hidden path="id"/><form:errors path="*" cssClass="text-danger d-block"/>
<label class="form-label">Tên đơn vị</label><form:input path="name" cssClass="form-control mb-3" maxlength="150"/>
<label class="form-label">Điện thoại</label><form:input path="phone" cssClass="form-control mb-3" maxlength="20"/>
<label class="form-label">Phí cơ bản (VND)</label><form:input path="baseFee" type="number" min="0" step="0.01" cssClass="form-control mb-3"/>
<label class="form-label">Số ngày dự kiến</label><form:input path="estimatedDays" type="number" min="1" max="365" cssClass="form-control mb-3"/>
<div class="form-check mb-3"><form:checkbox path="active" cssClass="form-check-input"/><label class="form-check-label">Đang hoạt động</label></div><button class="btn btn-primary">Lưu</button> <a href="${pageContext.request.contextPath}/manager/shipping-providers" class="btn btn-outline-secondary">Làm mới</a></form:form></div></div>
<div class="col-lg-7"><div class="table-responsive bg-white rounded"><table class="table"><thead><tr><th>Tên</th><th>Phí</th><th>Ngày</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach items="${providers}" var="provider"><tr><td><c:out value="${provider.name}"/></td><td>${provider.baseFee}</td><td>${provider.estimatedDays}</td><td>${provider.active ? 'Đang bật' : 'Đã tắt'}</td><td><a href="${pageContext.request.contextPath}/manager/shipping-providers?edit=${provider.id}">Sửa</a></td></tr></c:forEach></tbody></table></div></div></div></main></body></html>
