<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StarShop Quản trị</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light">
<nav class="navbar navbar-dark bg-dark"><div class="container d-flex gap-3 flex-wrap"><a class="navbar-brand" href="${pageContext.request.contextPath}/manager">StarShop Admin</a><div class="d-flex gap-3 flex-wrap"><a class="text-white" href="${pageContext.request.contextPath}/manager/shops">Shop</a><a class="text-white" href="${pageContext.request.contextPath}/manager/users">Người dùng</a><a class="text-white" href="${pageContext.request.contextPath}/manager/shipping-providers">Vận chuyển</a><a class="text-white" href="${pageContext.request.contextPath}/manager/orders">Đơn hàng</a></div></div></nav>
<main class="container py-4"><c:if test="${not empty success}"><div class="alert alert-success"><c:out value="${success}"/></div></c:if><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<h1 class="h3">Quản lý người dùng</h1><form class="d-flex gap-2 my-3" method="get"><input class="form-control" name="keyword" value="<c:out value='${keyword}'/>" placeholder="Tên hoặc email"><button class="btn btn-primary">Tìm kiếm</button></form>
<div class="table-responsive bg-white rounded shadow-sm"><table class="table align-middle"><thead><tr><th>Tên</th><th>Email</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${users.content}" var="account"><tr><td><c:out value="${account.fullName}"/></td><td><c:out value="${account.email}"/></td><td>${account.status}</td><td><c:if test="${account.status == 'ACTIVE' || account.status == 'LOCKED'}"><form method="post" action="${pageContext.request.contextPath}/manager/users/${account.id}/lock"><input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"><input type="hidden" name="locked" value="${account.status == 'ACTIVE'}"><button class="btn btn-sm btn-outline-secondary">${account.status == 'ACTIVE' ? 'Khóa' : 'Mở khóa'}</button></form></c:if></td></tr></c:forEach><c:if test="${users.isEmpty()}"><tr><td colspan="4" class="text-center">Không có tài khoản phù hợp</td></tr></c:if></tbody></table></div>
<nav class="mt-3"><ul class="pagination"><c:if test="${users.hasPrevious()}"><c:url var="prev" value="/manager/users"><c:param name="page" value="${users.number-1}"/><c:param name="keyword" value="${keyword}"/></c:url><li class="page-item"><a class="page-link" href="${prev}">Trước</a></li></c:if><li class="page-item disabled"><span class="page-link">${users.number+1} / ${users.totalPages == 0 ? 1 : users.totalPages}</span></li><c:if test="${users.hasNext()}"><c:url var="next" value="/manager/users"><c:param name="page" value="${users.number+1}"/><c:param name="keyword" value="${keyword}"/></c:url><li class="page-item"><a class="page-link" href="${next}">Sau</a></li></c:if></ul></nav></main></body></html>
